### ISSUE TITLE
Problème lors de la récupération de la date

### ISSUE THREAD

**Issue by kawoto** [Roromis/Lalf-Forumactif#15]
Bonsoir,
Je souhaite exporter mon forumactif pour cela j'utilise votre script.
Tout se passe bien jusqu'à la récupération des membres, je reçois cette erreur : 
06/05/2013 22:27:24 - INFO     : Récupération des membres
06/05/2013 22:27:26 - DEBUG    : Récupération : membre 1
06/05/2013 22:27:26 - ERROR    : Une erreur s'est produite. Essayez de relancer le script. Pour plus d'informations, consultez le fichier debug.log.
Traceback (most recent call last):
  File "C:\Users\Romain\Desktop\forum\forumactif-phpbb.py", line 436, in <module>
    etapes[i]()
  File "C:\Users\Romain\Desktop\forum\forumactif-phpbb.py", line 268, in get_users
    date = time.mktime(time.struct_time((int(date[2]),month[date[1]],int(date[0]),0,0,0,0,0,0)))
KeyError: u'D\xc3\xa9c'
06/05/2013 22:27:26 - INFO     : Sauvegarde de la progression

Pour essayer de contourner le problème, j'ai mis la même date d'inscription pour tout le monde en modifiant légèrement le script, résultat : ça marche.

Lorsque le script récupère les messages, à nouveau le problème des dates : 
06/05/2013 22:46:12 - ERROR    : Une erreur s'est produite. Essayez de relancer le script. Pour plus d'informations, consultez le fichier debug.log.
Traceback (most recent call last):
  File "C:\Users\Romain\Desktop\forum\forumactif-phpbb.py", line 436, in <module>
    etapes[i]()
  File "C:\Users\Romain\Desktop\forum\forumactif-phpbb.py", line 371, in get_posts
    timestamp = time.mktime(datetime.datetime(int(date[3]),month[date[2]],int(date[1]),int(date[5].split(":")[0]),int(date[5].split(":")[1])).timetuple())
KeyError: u'D\u0102\u0160c'
06/05/2013 22:46:12 - INFO     : Sauvegarde de la progression

J'ai bien mis le format de date qui est indiqué dans le readme. (La date/heure actuelle est Lun 6 Mai - 22:57)

Merci d'avance pour votre aide.

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'une ancienne version du Lalf.
