### ISSUE TITLE
Récup des membres : mauvaise récup de la page

### ISSUE THREAD

**Issue by Supermanu** [Roromis/Lalf-Forumactif#20]
Bonjour,
j'ai eu également un problème de récupération des membres. Ça n'a pas l'air d'être le problème d'encodage. D'abord, la ligne d'erreur n'est pas la même:

ERROR    : Une erreur s'est produite. Essayez de relancer le script. Pour plus d'informations, consultez le fichier debug.log.
Traceback (most recent call last):
  File "forumactif-phpbb.py", line 437, in <module>
    etapes[i]()
  File "forumactif-phpbb.py", line 265, in get_users
    id = int(re.search("&u=(\d+)&", e("td a").eq(0).attr("href")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

 Ensuite en fouillant un peu, j'ai remarqué que le simple fait de charger deux fois de suite la page avec d=PyQuery(…) ne donnait pas le même résultat (le d.text() n'est pas le même). La deuxième fois, je tombe sur la page d'accueil (comme si j'étais déconnecté).

C'est seulement en lui demandant de se reconnecter au forum après chaque page, qu'il arrive à prendre tous les membres. Ce n'est sûrement pas une solution à long terme mais ça fonctionne.

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'une ancienne version du Lalf.
