### ISSUE TITLE
Blocage récupération des membres

### ISSUE THREAD

**Issue by rico88** [Roromis/Lalf-Forumactif#21]
Bonjour,

J'ai testé le script et tout se passe impeccable jusqu'à la récupération des membres.

J'obtiens le message suivant dans le log:

19/08/2013 13:25:21 - DEBUG    : Récupération : membre 88
19/08/2013 13:25:21 - ERROR    : Une erreur s'est produite. Essayez de relancer le script. Pour plus d'informations, consultez le fichier debug.log.
Traceback (most recent call last):
  File "C:\Users\Eric\Desktop\Lalf-Forumactif-master\forumactif-phpbb.py", line 437, in <module>
    etapes[i]()
  File "C:\Users\Eric\Desktop\Lalf-Forumactif-master\forumactif-phpbb.py", line 269, in get_users
    date = time.mktime(time.struct_time((int(date[2]),month[date[1]],int(date[0]),0,0,0,0,0,0)))
KeyError: u'D\xc3\xa9c'

J'ai parcouru toutes les pages de problème mais aucune solution ne correspond à mon problème.

Merci d'avance pour votre aide :)

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'une ancienne version du Lalf.
