### ISSUE TITLE
Error 503 : Service Temporaly Unavailable

### ISSUE THREAD

**Issue by Flo2** [Roromis/Lalf-Forumactif#22]
Bonjour,

Je rencontre l'erreur citée en titre lorsque je lance le script.
J'ai beau le laisser aller et le relancer une fois ses 10 tentatives terminées, rien n'y fait, ça plante toujours durant la récupération des forums.
La progression se fait de manière aléatoire, un coup il me récupère 45/148 forums, un coup 80/148.

Ce qui est dommage c'est qu'à chaque fois il repart de 0. Si le script repartait de là où il s'est arrêté la dernière fois il y arriverait au final (je ne sais pas si le comportement que j'ai, à savoir que ça recommence à chaque fois est normal ou pas).

Quelqu'un aurait-il une idée sur la marche à suivre ?

Merci d'avance,

Florent

**Comment by Lesime** [comment]
Bonjour Florent, 

Je rencontre le même problème que vous, et ça fait plusieurs jours que je le relance presque tout le temps, sans succès :/

Auriez-vous quelques informations qui pourraient m'aider ?

Merci d'avance,
Lesime
