### ISSUE TITLE
Problème d'encodage avec la version 3

### ISSUE THREAD

**Issue by ArnoHolo** [Roromis/Lalf-Forumactif#29]
Bonjour !

Je teste la version 3 sortie il y a 10 jours (je ne sais pas si elle est terminée ?).

J'ai plusieurs problèmes avec les accents dans les fichiers, du coup je remplace chaque accent par la lettre sans accent correspondante. Et le problème s'en va. Cependant j'ai tout de même le problème suivant : 

File "/home/me/Bureau/Lalf-Forumactif-3/lalf/forum.py", line 29
SyntaxError: Non-ASCII character '\xc3' in file /home/me/Bureau/Lalf-Forumactif-3/lalf/forum.py on line 30, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Une idée ? Merci !

**Comment by elsasskiting** [comment]
Bonjour, 
nous sommes une association de kitesurf alsacienne, nous sommes sur forumactif depuis 2006.
Nous voudrions migrer le forum dans notre propre base de donnée.
Roromis seriez vous capable d'effectuer cette opération ? 
Ce travail serait rémunéré.
Cordialement
