### ISSUE TITLE
Problèmes Lalf 3

### ISSUE THREAD

**Issue by Prunell** [Roromis/Lalf-Forumactif#34]
Bonjours à tous !
Bon... J'ai installe Python 3.2 (Parce que Lxml ne marche pas sur Python 3.4), ainsi que Pip et le Lalf.
J'ai un fichier sur le Bureau avec tous les fichiers du Lalf 3 disponible sur GitHub, et je lance : C:\Python32\python.exe lalf.py

Mais j'ai cette erreur au démarrage :
Traceback (most recent call last):
  File "lalf.py", line 19, in <module>
    from lalf import main
  File "C:\Users\****\Desktop\Serveur Minecraft\PhpBB\Forum Actif\Lalf 3.
 Roromis\lalf\__init__.py", line 28, in <module>
    from lalf.bb import load, BB
  File "C:\Users\****\Desktop\Serveur Minecraft\PhpBB\Forum Actif\Lalf 3.
 Roromis\lalf\bb.py", line 30, in <module>
    from lalf.forums import Forums
  File "C:\Users\****\Desktop\Serveur Minecraft\PhpBB\Forum Actif\Lalf 3.
 Roromis\lalf\forums.py", line 25, in <module>
    from lalf.forum import Forum
  File "C:\Users\****\Desktop\Serveur Minecraft\PhpBB\Forum Actif\Lalf 3.
 Roromis\lalf\forum.py", line 29, in <module>
    from lalf.forumpage import ForumPage
  File "C:\Users\****\Desktop\Serveur Minecraft\PhpBB\Forum Actif\Lalf 3.
 Roromis\lalf\forumpage.py", line 64
    locked = u"verrouillé" in f("td img").eq(0).attr("alt")
                          ^
SyntaxError: invalid syntax

Quelqu'un a une idée ?

**Comment by Rotschreck** [comment]
Ma réponse vient peut être un peu tard mais:

Le Lxml fonctionne avec Python 3.4.3. Va récupérer cette version de python et le lxml-3.4.4-cp34-none-win32.whl sur le repository (une recherche dans ton browser préféré va te donner le lien)
Ensuite, un "pip install lxml-3.4.4-cp34-none-win32.whl" avec le bon chemin t'installera la librairie précompilée

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'une ancienne version du Lalf. Si vous avez ce problème avec la dernière version, ouvrez un nouveau rapport de bug.
