### ISSUE TITLE
Pas d'importation topics /post sans erreur...

### ISSUE THREAD

**Issue by DarkEagle37** [Roromis/Lalf-Forumactif#35]
Bonjour,
Après avoir tenté de nombreuses fois d’exécuter ce script, je finis parvenir demander de l'aide par ici...

Je l'utilises sous Windows 7, j'ai fait toutes les manips décrites dans le readme.txt. J’utilise la version 2 de Lalf, avec la version de MathieuMa.
Tout fonctionne très bien, j'arrive à exporter mes 3707 membres (ça prends quand même du temps..obligé de rafraichir la page d'admin où l'on voit les utilisateurs pour que le script continue..).
Mon problème c'est qu'une fois fini l'importation des membres, il commence à importer les POST/TOPIC..... et s'arrête quasi instantanément, et sans messages d'erreur !

Et donc finalement il me dit que c'est fini, génère le phpbb.sql et c'est tout !
Voici le fichier save.py
```
# -*- coding: utf-8 -*-

state = 6

nbposts = 43246
nbtopics = 3268
nbusers = 3707

topics = []

posts = []
```
Les utilisateurs sont bien tous importé, les émoticône (super...) aussi,ainsi que les forums, mais pas les post et les topics...

Voici la fin du fichier debug...

```
28/07/2014 06:20:51 - DEBUG    : Récupération : membre 3709
28/07/2014 06:20:51 - INFO     : Récupération des émoticones
28/07/2014 06:20:55 - INFO     : Récupération des messages
28/07/2014 06:20:55 - DEBUG    : Sauvegarde de la progression
28/07/2014 06:20:55 - INFO     : Fin de la récupération
28/07/2014 06:20:55 - INFO     : Génération du fichier SQL
28/07/2014 06:20:55 - INFO     : L'exportation a été effectuée avec succés. Vous pouvez à présent importer le fichier phpbb.sql dans votre base de donnée (après avoir installé phpbb3).
```
Et on voit bien au début du fichier deug que le script à bien détecté les 43203 mesages:
```
27/07/2014 16:37:32 - INFO     : Migration Forumactif -> PhpBB : Lalf 0.2.1
27/07/2014 16:37:32 - DEBUG    : Importation des bibliothèques
27/07/2014 16:37:33 - DEBUG    : Importation de la sauvegarde
27/07/2014 16:37:33 - DEBUG    : Pas de sauvegarde disponible : création d'une sauvegarde vide
27/07/2014 16:37:33 - DEBUG    : Création de l'urlopener
27/07/2014 16:37:33 - INFO     : Connection au forum
27/07/2014 16:37:34 - DEBUG    : Récupération du sid
27/07/2014 16:37:34 - DEBUG    : Récupération du tid
27/07/2014 16:37:36 - INFO     : Récupération des statistiques
27/07/2014 16:37:39 - DEBUG    : Messages : 43203
27/07/2014 16:37:39 - DEBUG    : Sujets : 3266
```
J'ai essayé en mettant le forum en maintenance, même problème... et tout ça sans message d'erreur...

**Comment by Roromis** [comment]
Bug corrigé dans la dernière version.
