### ISSUE TITLE
Problème d'import de l'adresse mail

### ISSUE THREAD

**Issue by jeancf** [Roromis/Lalf-Forumactif#36]
Pour tous les utilisateurs dont le nom comporte des caractères non ASCII (accentués par exemple) l'application est incapable d'importer automatiquement l'adresse mail. Exemples:

    INFO     : L'adresse email de l'utilisateur Malaussène n'a pas pu être exportée.
    INFO     : L'adresse email de l'utilisateur töbi n'a pas pu être exportée.

Heureusement il y en a peu et l'application offre l'option d'introduire l'adresse à la main. Bien vu!

**Comment by Roromis** [comment]
Je n'arrive pas à reproduire ce bug.

Si vous rencontrez ce problème, n'hésitez pas à vous manifester, j'essayerai de vous aidez à le corriger.

**Comment by Roromis** [comment]
Corrigé (7c76aba). Pour l'instant cette correction n'est disponible que dans la branche develop (que je vous déconseille d'utiliser), je devrais pouvoir la merger dans la branche develop assez rapidement.
