### ISSUE TITLE
Problème avec les Membres

### ISSUE THREAD

**Issue by EspritOrgue** [Roromis/Lalf-Forumactif#40]
Bonjour,

J'utilise le code que j'ai trouvé récemment pour prendre les infos sur un forum qui a déjà quelques annnées derrière lui et donc pas mal de membres et de messages.

La partie pour les catégorie est nickel, mais le code coince aux membre avec cette erreur:
```  python
Traceback (most recent call last):
File "C:\Users\amir\Desktop\RecuperationNS\LalfVersMatthieu\Lalf-Forumactif-master\forumactif-phpbb.py", line 564, in <module>
    etapes[i]()
  File "C:\Users\amir\Desktop\RecuperationNS\LalfVersMatthieu\Lalf-Forumactif-master\forumactif-phpbb.py", line 318, in get_users
    raise RuntimeError('Forum user page in "import proteced" mode - cannot process users...')
RuntimeError: Forum user page in "import proteced" mode - cannot process users...
```
Toutefois, j'ai trouvé une autre solution, qui fonctionne, mais j'aimerai continuer à utiliser ce code pour récupérer catégorie et posts/sujets, bbcodes, etc.

Mais ne m'y connaissant pas vraiment en python... 
Y a-t-il moyen de virer la partie membre et passer directement à la suivante?

Merci d'avance.

**Comment by Roromis** [comment]
Je ferme ce rapport de bug qui est à propos d'une ancienne version.

Si tu veux toujours exporter ton forum, essaye de suivre la nouvelle [documentation](https://roromis.github.io/Lalf-Forumactif/introduction).
