### ISSUE TITLE
ImportError : Cannont import name main

### ISSUE THREAD

**Issue by Shidesu** [Roromis/Lalf-Forumactif#42]
Bonjour,
j'ai récemment tenté d'utiliser le lalf 3 et je suis tombé sur une erreur que je ne comprends pas et je n'arrive donc pas à m'en sortir. Lorsque je lance lalf.py depuis l'invite de commande, je reçois l'erreur suivante : 
Traceback (most recent call last):
  File "C:\python32\scripts\lalf.py", line 3, in <module>
    from lalf import __main__
  File "C:\python32\scripts\lalf.py", line 3, in <module>
    from lalf import __main__
ImportError: cannot import name __main__

Si quelqu'un est capable de m'aider, je le remercie d'avance...

**Comment by Roromis** [comment]
Ce bug devrait être corrigé dans la dernière version, si ce n'est pas le cas tu peux rouvrir l'issue.
