### ISSUE TITLE
Problème d'encodage

### ISSUE THREAD

**Issue by marmottin** [Roromis/Lalf-Forumactif#43]
Petit souci à la fin de l'export avec la v3 du script.
Tout fonctionne correctement jusqu'à la fin du processus, une fois tous les membres, sujets et messages exportés.

Message indiqué : 
`File "D:\Python34\lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 359-360: character maps to <undefined>`

J'ai quand même un fichier SQL que je peux importer, mais les quelques messages qui passent ne sont pas encodés correctement (? au lieu des caractères spéciaux), quand ils ne sont pas simplement tronqués.

Le tout sous Windows 7 x64 avec : 
- python 3.4.3 x64
- lxml 3.4.4
- pyquery récupéré directement avec pip
- requests 2.7.0
- pypng 0.0.17

**Comment by Rotschreck** [comment]
Salut.
J'ai le meme souci que toi avec la meme config. 
Je ne sais pas si tu as réglé ton souci.

**Comment by marmottin** [comment]
Malheureusement non, je n'ai guère pris le temps de rechercher.
Quelques correctifs ont été apportés ces derniers jours et de nouvelles versions des dépenses sont aussi dispo.
Je ré-essayerai à l'occasion :)

**Comment by Roromis** [comment]
J'ai finalement pris le temps de faire des tests sous Windows, ce bug est corrigé dans la dernière version.
