### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' (utilisation d'un thème temporaire)

### ISSUE THREAD

**Issue by xouxouxx** [Roromis/Lalf-Forumactif#46]
Bonjour,

j'ai le même souci qu'ici #45  mais moi c'est sous Windows et surtout j'ai la dernière version que je viens d'installer.

Je n'arrive même pas à récupérer les membres que le message d'erreur s'affiche : 

`INFO     : Récupération des membres
DEBUG    : Récupération des membres (page 0)
INFO     : Sauvegarde de l'état courant.
ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (AttributeError("'NoneType' object has no attribute 'group'",)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
https://github.com/Roromis/Lalf-Forumactif/issues
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\lalf\__init__.py", line 58, in main
    bb.export()
  File "C:\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
    child.export()
  File "C:\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
    child.export()
  File "C:\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
    self._export_()
  File "C:\Miniconda3\lib\site-packages\lalf\ocrusers.py", line 244, in _export_
    oldid = int(urlpattern.fullmatch(e("td a").eq(0).attr("href")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'`

J'avais déjà réussi une exportation du forum il y a deux semaines et j'étais partit aujourd'hui pour refaire pareil avec la version mise à jour mais là j'avoue que je ne comprends pas.

L'installation s'est très bien passée via pip et j'utilise exactement la version décrite dans la procédure.

En vous remerciant pour votre formidable travail

[debug.txt](https://github.com/Roromis/Lalf-Forumactif/files/200770/debug.txt)

**Comment by xouxouxx** [comment]
J'ai trouvé par moi même, c'est apparemment l'utilisation de la fonction thème temporaire que soit j'ai mal exécuté soit qui ne fonctionne pas.

**Comment by Roromis** [comment]
Bonjour,

comment avez vous résolu le problème?

**Comment by xouxouxx** [comment]
Simplement sans utiliser la fonction thème temporaire, j'ai changé l'intégralité de mon forum vers le thème générique de phpbb2 et le tour était joué (enfin il reste encore 142 000 messages à copier mais c'est en cours :) )

**Comment by Roromis** [comment]
Étrange, si vous ouvrez la page `*votre forum*/memberlist?change_temp=1` (en remplaçant 1 par le numéro du thème temporaire, voir la [documentation](https://roromis.github.io/Lalf-Forumactif/annexes/theme-temporaire.html)), le thème temporaire est-il bien appliqué?

**Comment by xouxouxx** [comment]
Oui, mais je pousserai les tests une fois l'exportation terminé.

**Comment by Roromis** [comment]
J'ai fait des tests, et effectivement j'ai ce problème aussi avec un thème temporaire. C'est encore une fois une erreur bête. Il faut absolument que je trouve un moyen de tester automatiquement et efficacement mon code.

Je corrigerai d'ici quelques jours.
