### ISSUE TITLE
Erreur avec l'e-mail d'un utilisateur

### ISSUE THREAD

**Issue by ArnoHolo** [Roromis/Lalf-Forumactif#48]
L'extraction des posts a l'air de fonctionner correctement et jusqu'au bout. Cependant je tombe sur l'erreur ci-dessous à un moment.

Je viens de vérifier sur le forum, cette adresse est écrite en majuscule, exemple : XXXX@HOTMAIL.FR. C'est peut-être la cause du problème ?

```
L'adresse email de l'utilisateur xxxxx n'a pas pu être exportée.

  File "lalf.py", line 22, in <module>
    main()
  File "/Users/ad/Workspace/Lalf-Forumactif-master/lalf/__init__.py", line 71, in main
    user.confirm_email()
  File "/Users/ad/Workspace/Lalf-Forumactif-master/lalf/ocrusers.py", line 212, in confirm_email
    self._export_(False)
TypeError: _export_() takes 1 positional argument but 2 were given
```

Question subsidiaire : J'ai essayé de relancer le script plusieurs fois, et il a l'air de ré-extraire quelques messages du forum, avant de s'attaquer aux utilisateurs et afficher à nouveau cette erreur. En gros, quand je relance, ça recommence l'extraction au niveau 99% jusqu'à 100%. Ça a l'air d'extraire les messages venant des mêmes topics, n'y a-t-il pas un risque de doublons ? (Je n'ai pas encore vérifié le fichier d'output.)

EDIT : Humph, je viens de voir [cette issue](https://github.com/Roromis/Lalf-Forumactif/issues/36), c'est peut-être lié ?

**Comment by Roromis** [comment]
Il y a plusieurs problèmes.

Le problème principal a déjà été signalé dans l'issue #47. Fais une copie du fichier save.pickle au cas où, met à jour le script:

 - avec git : `git pull`
 - avec pip : `pip install -U https://github.com/Roromis/Lalf-Forumactif/archive/master.zip`
 - à la main : de la même manière que pour l'installation, en faisant attention à ne pas écraser le fichier `config.cfg`.

et relance le. Le script t'indiquera toujours que "L'adresse email de l'utilisateur xxxxx n'a pas pu être exportée.", mais cette fois tu auras la possibilité de la saisir manuellement.

S'il y a des caractères spéciaux (lettres accentuées, symboles non ASCII...) dans le nom de l'utilisateur, alors oui c'est aussi un doublon de l'issue #36. Ce bug est résolu dans la branche develop, mais je te déconseille de l'utiliser pour le moment, j'y ai fait pas mal de modifications, et les fichiers de sauvegarde et de configuration ne sont pas compatible avec la version que tu utilises.

Une fois l'exportation réussie, vérifie que tu n'as pas de problèmes d'encodage (en particulier dans les noms d'utilisateurs et de groupes). Si tu en as signale le moi.

**Comment by ArnoHolo** [comment]
Effectivement, la dernière version ne le fait plus. (Je n'ai même pas eu à entrer une adresse à la main.)

Merci !
