### ISSUE TITLE
Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by Lemmy1916** [Roromis/Lalf-Forumactif#51]
Bonsoir,

Tout d'abord merci, grâce à vous j'avais il y à quelques année pu déménager un de mes forums qui aujourd'hui se porte très bien. J'ai vu que votre logiciel était de nouveau à jour et il me reste encore deux forum que 'j’aimerai pouvoir récupérer mais voilà, ma première tentative est un échec :

> INFO     : Lalf 3.0a0
> DEBUG    : OS : win32
> INFO     : Récupération des statistiques
> INFO     : Sauvegarde de l'état courant.
> ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (ConnectionError(MaxRetryError("HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //monforum.forumactif.fr//statistics (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000022ACCA3E390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))",),)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
> https://github.com/Roromis/Lalf-Forumactif/issues
> Traceback (most recent call last):
>   File "C:\Users\moi\Miniconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 137, in _new_conn
>     (self.host, self.port), self.timeout, **extra_kw)
>   File "C:\Users\moi\Miniconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 67, in create_connection
>     for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
>   File "C:\Users\luc\Miniconda3\lib\socket.py", line 732, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 11001] getaddrinfo failed

Etc etc ...

Merci d'avance à ceux qui se donnerons la peine de m'aider ;)

**Comment by Roromis** [comment]
Bonjour,

dans le fichier `config.cfg`, l'adresse du forum doit-être au format `monforum.forumactif.fr`, et non `http://monforum.forumactif.fr/`. Je pense que ton problème viens de là.

**Comment by Lemmy1916** [comment]
Bonjour,

je me suis aperçu du problème et corrigé à la 3eme tentative mais sans succès, toujours le même problème (voir log). Merci pour la réponse rapide en tout cas.

**Comment by Roromis** [comment]
Est-ce vraiment exactement la même erreur? Peux-tu supprimer le fichier `debug.log`, relancer le script, et m'envoyer le contenu du nouveau fichier `debug.log`

**Comment by Lemmy1916** [comment]
Ce sera fait dès mon retour du boulot en soirée, encore merci !

**Comment by Lemmy1916** [comment]
Bonsoir,

il s'agissait bien d'une erreur de ma part ! Je clos donc mais je refait un topic puisque j'ai un nouveau soucis xD
