### ISSUE TITLE
La connexion a échoué au moins deux fois ...

### ISSUE THREAD

**Issue by Lemmy1916** [Roromis/Lalf-Forumactif#52]
Bonsoir,

je vous présente mon petit soucis, j'ai clos l'ancien topic il s’agissait d'une erreur de ma part, la par contre je ne comprend pas le soucis. 

> INFO     : Lalf 3.0a0
> DEBUG    : OS : win32
> INFO     : Récupération des statistiques
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> DEBUG    : Récupération du tid
> DEBUG    : Messages : 8005
> DEBUG    : Sujets : 1042
> DEBUG    : Membres : 10087
> INFO     : Récupération des émoticones
> DEBUG    : Récupération des émoticones (page 0)
> DEBUG    : L'émoticone ":D" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":)" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":(" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":o" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":shock:" existe déjà dans phpbb.
> DEBUG    : L'émoticone "8)" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":lol:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":x" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":P" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":oops:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":cry:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":evil:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":twisted:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":roll:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ";)" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":!:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":?:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":idea:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":arrow:" existe déjà dans phpbb.
> DEBUG    : L'émoticone ":|" existe déjà dans phpbb.
> DEBUG    : Récupération des émoticones (page 20)
> INFO     : Téléchargement de l'émoticone ":face:"
> INFO     : Téléchargement de l'émoticone ":star:"
> INFO     : Téléchargement de l'émoticone ":suspect:"
> INFO     : Téléchargement de l'émoticone ":heart:"
> INFO     : Téléchargement de l'émoticone ":no:"
> INFO     : Téléchargement de l'émoticone ":@:"
> INFO     : Téléchargement de l'émoticone ":cyclops:"
> INFO     : Téléchargement de l'émoticone ":clown:"
> INFO     : Téléchargement de l'émoticone ":pirat:"
> INFO     : Téléchargement de l'émoticone ":tongue:"
> INFO     : Téléchargement de l'émoticone ":silent:"
> INFO     : Téléchargement de l'émoticone ":pale:"
> INFO     : Téléchargement de l'émoticone ":alien:"
> INFO     : Téléchargement de l'émoticone ":cat:"
> INFO     : Téléchargement de l'émoticone ":monkey:"
> INFO     : Téléchargement de l'émoticone ":pig:"
> INFO     : Téléchargement de l'émoticone ":rabbit:"
> INFO     : Téléchargement de l'émoticone ":bounce:"
> INFO     : Téléchargement de l'émoticone ":confused:"
> INFO     : Téléchargement de l'émoticone ":affraid:"
> DEBUG    : Récupération des émoticones (page 40)
> DEBUG    : L'émoticone ":geek:" existe déjà dans phpbb.
> INFO     : Téléchargement de l'émoticone ":bball:"
> INFO     : Téléchargement de l'émoticone ":cheers:"
> INFO     : Téléchargement de l'émoticone ":bom:"
> INFO     : Téléchargement de l'émoticone ":drunken:"
> INFO     : Téléchargement de l'émoticone ":sleep:"
> INFO     : Téléchargement de l'émoticone ":sunny:"
> INFO     : Téléchargement de l'émoticone ":albino:"
> INFO     : Téléchargement de l'émoticone ":cherry:"
> INFO     : Téléchargement de l'émoticone ":santa:"
> INFO     : Téléchargement de l'émoticone ":rendeer:"
> INFO     : Téléchargement de l'émoticone ":farao:"
> INFO     : Téléchargement de l'émoticone ":king:"
> INFO     : Téléchargement de l'émoticone ":queen:"
> INFO     : Téléchargement de l'émoticone ":joker:"
> INFO     : Téléchargement de l'émoticone ":scratch:"
> INFO     : Téléchargement de l'émoticone ":study:"
> INFO     : Téléchargement de l'émoticone ":elephant:"
> INFO     : Téléchargement de l'émoticone ":flower:"
> INFO     : Téléchargement de l'émoticone ":afro:"
> DEBUG    : Récupération des émoticones (page 60)
> INFO     : Téléchargement de l'émoticone ":lol!:"
> INFO     : Récupération des membres
> DEBUG    : Récupération des membres (page 0)
> DEBUG    : Récupération des membres (page 50)
> DEBUG    : Récupération des membres (page 100)
> DEBUG    : Récupération des membres (page 150)
> DEBUG    : Récupération des membres (page 200)
> DEBUG    : Récupération des membres (page 250)
> DEBUG    : Récupération des membres (page 300)
> DEBUG    : Récupération des membres (page 350)
> DEBUG    : Récupération des membres (page 400)
> DEBUG    : Récupération des membres (page 450)
> DEBUG    : Récupération des membres (page 500)
> DEBUG    : Récupération des membres (page 550)
> DEBUG    : Récupération des membres (page 600)
> DEBUG    : Récupération des membres (page 650)
> DEBUG    : Récupération des membres (page 700)
> DEBUG    : Récupération des membres (page 750)
> DEBUG    : Récupération des membres (page 800)
> DEBUG    : Récupération des membres (page 850)
> DEBUG    : Récupération des membres (page 900)
> DEBUG    : Récupération des membres (page 950)
> DEBUG    : Récupération des membres (page 1000)
> DEBUG    : Récupération des membres (page 1050)
> DEBUG    : Récupération des membres (page 1100)
> DEBUG    : Récupération des membres (page 1150)
> DEBUG    : Récupération des membres (page 1200)
> DEBUG    : Récupération des membres (page 1250)
> DEBUG    : Récupération des membres (page 1300)
> DEBUG    : Récupération des membres (page 1350)
> DEBUG    : Récupération des membres (page 1400)
> DEBUG    : Récupération des membres (page 1450)
> DEBUG    : Récupération des membres (page 1500)
> DEBUG    : Récupération des membres (page 1550)
> DEBUG    : Récupération des membres (page 1600)
> DEBUG    : Récupération des membres (page 1650)
> DEBUG    : Récupération des membres (page 1700)
> DEBUG    : Récupération des membres (page 1750)
> DEBUG    : Récupération des membres (page 1800)
> DEBUG    : Récupération des membres (page 1850)
> DEBUG    : Récupération des membres (page 1900)
> DEBUG    : Récupération des membres (page 1950)
> DEBUG    : Récupération des membres (page 2000)
> DEBUG    : Récupération des membres (page 2050)
> DEBUG    : Récupération des membres (page 2100)
> DEBUG    : Récupération des membres (page 2150)
> DEBUG    : Récupération des membres (page 2200)
> DEBUG    : Récupération des membres (page 2250)
> DEBUG    : Récupération des membres (page 2300)
> DEBUG    : Récupération des membres (page 2350)
> DEBUG    : Récupération des membres (page 2400)
> DEBUG    : Récupération des membres (page 2450)
> DEBUG    : Récupération des membres (page 2500)
> DEBUG    : Récupération des membres (page 2550)
> DEBUG    : Récupération des membres (page 2600)
> DEBUG    : Récupération des membres (page 2650)
> DEBUG    : Récupération des membres (page 2700)
> DEBUG    : Récupération des membres (page 2750)
> DEBUG    : Récupération des membres (page 2800)
> DEBUG    : Récupération des membres (page 2850)
> DEBUG    : Récupération des membres (page 2900)
> DEBUG    : Récupération des membres (page 2950)
> DEBUG    : Récupération des membres (page 3000)
> DEBUG    : Récupération des membres (page 3050)
> DEBUG    : Récupération des membres (page 3100)
> DEBUG    : Récupération des membres (page 3150)
> DEBUG    : Récupération des membres (page 3200)
> DEBUG    : Récupération des membres (page 3250)
> DEBUG    : Récupération des membres (page 3300)
> DEBUG    : Récupération des membres (page 3350)
> DEBUG    : Récupération des membres (page 3400)
> DEBUG    : Récupération des membres (page 3450)
> DEBUG    : Récupération des membres (page 3500)
> DEBUG    : Récupération des membres (page 3550)
> DEBUG    : Récupération des membres (page 3600)
> DEBUG    : Récupération des membres (page 3650)
> DEBUG    : Récupération des membres (page 3700)
> DEBUG    : Récupération des membres (page 3750)
> DEBUG    : Récupération des membres (page 3800)
> DEBUG    : Récupération des membres (page 3850)
> DEBUG    : Récupération des membres (page 3900)
> DEBUG    : Récupération des membres (page 3950)
> DEBUG    : Récupération des membres (page 4000)
> DEBUG    : Récupération des membres (page 4050)
> DEBUG    : Récupération des membres (page 4100)
> DEBUG    : Récupération des membres (page 4150)
> DEBUG    : Récupération des membres (page 4200)
> DEBUG    : Récupération des membres (page 4250)
> DEBUG    : Récupération des membres (page 4300)
> DEBUG    : Récupération des membres (page 4350)
> DEBUG    : Récupération des membres (page 4400)
> DEBUG    : Récupération des membres (page 4450)
> DEBUG    : Récupération des membres (page 4500)
> DEBUG    : Récupération des membres (page 4550)
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> CRITICAL : Échec de la connection.
> INFO     : La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> DEBUG    : Récupération du tid
> DEBUG    : Récupération des membres (page 4600)
> DEBUG    : Récupération des membres (page 4650)
> DEBUG    : Récupération des membres (page 4700)
> DEBUG    : Récupération des membres (page 4750)
> DEBUG    : Récupération des membres (page 4800)
> DEBUG    : Récupération des membres (page 4850)
> DEBUG    : Récupération des membres (page 4900)
> DEBUG    : Récupération des membres (page 4950)
> DEBUG    : Récupération des membres (page 5000)
> DEBUG    : Récupération des membres (page 5050)
> DEBUG    : Récupération des membres (page 5100)
> DEBUG    : Récupération des membres (page 5150)
> DEBUG    : Récupération des membres (page 5200)
> DEBUG    : Récupération des membres (page 5250)
> DEBUG    : Récupération des membres (page 5300)
> DEBUG    : Récupération des membres (page 5350)
> DEBUG    : Récupération des membres (page 5400)
> DEBUG    : Récupération des membres (page 5450)
> DEBUG    : Récupération des membres (page 5500)
> DEBUG    : Récupération des membres (page 5550)
> DEBUG    : Récupération des membres (page 5600)
> DEBUG    : Récupération des membres (page 5650)
> DEBUG    : Récupération des membres (page 5700)
> DEBUG    : Récupération des membres (page 5750)
> DEBUG    : Récupération des membres (page 5800)
> DEBUG    : Récupération des membres (page 5850)
> DEBUG    : Récupération des membres (page 5900)
> DEBUG    : Récupération des membres (page 5950)
> DEBUG    : Récupération des membres (page 6000)
> DEBUG    : Récupération des membres (page 6050)
> DEBUG    : Récupération des membres (page 6100)
> DEBUG    : Récupération des membres (page 6150)
> DEBUG    : Récupération des membres (page 6200)
> DEBUG    : Récupération des membres (page 6250)
> DEBUG    : Récupération des membres (page 6300)
> DEBUG    : Récupération des membres (page 6350)
> DEBUG    : Récupération des membres (page 6400)
> DEBUG    : Récupération des membres (page 6450)
> DEBUG    : Récupération des membres (page 6500)
> DEBUG    : Récupération des membres (page 6550)
> DEBUG    : Récupération des membres (page 6600)
> DEBUG    : Récupération des membres (page 6650)
> DEBUG    : Récupération des membres (page 6700)
> DEBUG    : Récupération des membres (page 6750)
> DEBUG    : Récupération des membres (page 6800)
> DEBUG    : Récupération des membres (page 6850)
> DEBUG    : Récupération des membres (page 6900)
> DEBUG    : Récupération des membres (page 6950)
> DEBUG    : Récupération des membres (page 7000)
> DEBUG    : Récupération des membres (page 7050)
> DEBUG    : Récupération des membres (page 7100)
> DEBUG    : Récupération des membres (page 7150)
> DEBUG    : Récupération des membres (page 7200)
> DEBUG    : Récupération des membres (page 7250)
> DEBUG    : Récupération des membres (page 7300)
> DEBUG    : Récupération des membres (page 7350)
> DEBUG    : Récupération des membres (page 7400)
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> CRITICAL : Échec de la connection.
> INFO     : La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> DEBUG    : Récupération du tid
> DEBUG    : Récupération des membres (page 7450)
> DEBUG    : Récupération des membres (page 7500)
> DEBUG    : Récupération des membres (page 7550)
> DEBUG    : Récupération des membres (page 7600)
> DEBUG    : Récupération des membres (page 7650)
> DEBUG    : Récupération des membres (page 7700)
> DEBUG    : Récupération des membres (page 7750)
> DEBUG    : Récupération des membres (page 7800)
> DEBUG    : Récupération des membres (page 7850)
> DEBUG    : Récupération des membres (page 7900)
> DEBUG    : Récupération des membres (page 7950)
> DEBUG    : Récupération des membres (page 8000)
> DEBUG    : Récupération des membres (page 8050)
> DEBUG    : Récupération des membres (page 8100)
> DEBUG    : Récupération des membres (page 8150)
> DEBUG    : Récupération des membres (page 8200)
> DEBUG    : Récupération des membres (page 8250)
> DEBUG    : Récupération des membres (page 8300)
> DEBUG    : Récupération des membres (page 8350)
> DEBUG    : Récupération des membres (page 8400)
> DEBUG    : Récupération des membres (page 8450)
> DEBUG    : Récupération des membres (page 8500)
> DEBUG    : Récupération des membres (page 8550)
> DEBUG    : Récupération des membres (page 8600)
> DEBUG    : Récupération des membres (page 8650)
> DEBUG    : Récupération des membres (page 8700)
> DEBUG    : Récupération des membres (page 8750)
> DEBUG    : Récupération des membres (page 8800)
> DEBUG    : Récupération des membres (page 8850)
> DEBUG    : Récupération des membres (page 8900)
> DEBUG    : Récupération des membres (page 8950)
> DEBUG    : Récupération des membres (page 9000)
> DEBUG    : Récupération des membres (page 9050)
> DEBUG    : Récupération des membres (page 9100)
> DEBUG    : Récupération des membres (page 9150)
> DEBUG    : Récupération des membres (page 9200)
> DEBUG    : Récupération des membres (page 9250)
> DEBUG    : Récupération des membres (page 9300)
> DEBUG    : Récupération des membres (page 9350)
> DEBUG    : Récupération des membres (page 9400)
> DEBUG    : Récupération des membres (page 9450)
> DEBUG    : Récupération des membres (page 9500)
> DEBUG    : Récupération des membres (page 9550)
> DEBUG    : Récupération des membres (page 9600)
> DEBUG    : Récupération des membres (page 9650)
> DEBUG    : Récupération des membres (page 9700)
> DEBUG    : Récupération des membres (page 9750)
> DEBUG    : Récupération des membres (page 9800)
> DEBUG    : Récupération des membres (page 9850)
> DEBUG    : Récupération des membres (page 9900)
> DEBUG    : Récupération des membres (page 9950)
> DEBUG    : Récupération des membres (page 10000)
> DEBUG    : Récupération des membres (page 10050)
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> CRITICAL : Échec de la connection.
> INFO     : La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> DEBUG    : Récupération du tid
> INFO     : Récupération des groupes
> INFO     : Récupération du groupe 1
> DEBUG    : Récupération du groupe 1 (page 0)
> INFO     : Sauvegarde de l'état courant.
> ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (KeyError(1,)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
> https://github.com/Roromis/Lalf-Forumactif/issues
> Traceback (most recent call last):
>   File "C:\Users\moi\Miniconda3\lib\site-packages\lalf\__init__.py", line 58, in main
>     bb.export()
>   File "C:\Users\luc\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
>     child.export()
>   File "C:\Users\moi\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
>     child.export()
>   File "C:\Users\moi\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
>     child.export()
>   File "C:\Users\moi\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
>     self._export_()
>   File "C:\Users\moi\Miniconda3\lib\site-packages\lalf\groups.py", line 67, in _export_
>     user = self.users[int(match.group(1))]
> KeyError: 1
>

**Comment by Roromis** [comment]
Visiblement aucun membre n'est exporté...

Tu utilises bien un thème phpbb2? Dans tous les cas, essaye d'utiliser un [thème temporaire](https://roromis.github.io/Lalf-Forumactif/annexes/theme-temporaire.html).

Supprime le fichier `save.pickle` avant de lancer le script. Une fois que le message "Récupération des membres" est affiché dans la console, attends quelques minutes, il devrait y avoir des messages "Récupération du membre *n*". Si ce n'est pas le cas préviens moi, et tu peux interrompre le script.

**Comment by Lemmy1916** [comment]
C'était exactement ça, faudrait que j'apprenne à lire correctement un tuto en fait ! Merci
