### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Lemmy1916** [Roromis/Lalf-Forumactif#53]
Bonjour,

tout allai bien jusqu'à ce moment, après la récupération des membres/groupes. Encore merci pour l'aide apporté :+1: 

> DEBUG    : Récupération du groupe 4 (page 9950)
> DEBUG    : Récupération du groupe 4 (page 10000)
> DEBUG    : Récupération du groupe 4 (page 10050)
> INFO     : Récupération des forums
> INFO     : Sauvegarde de l'état courant.
> ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (IndexError('list index out of range',)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
> https://github.com/Roromis/Lalf-Forumactif/issues
> Traceback (most recent call last):
>   File "C:\Users\luc\Miniconda3\lib\site-packages\lalf\__init__.py", line 58, in main
>     bb.export()
>   File "C:\Users\luc\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
>     child.export()
>   File "C:\Users\luc\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
>     self._export_()
>   File "C:\Users\luc\Miniconda3\lib\site-packages\lalf\forums.py", line 217, in _export_
>     parent = depths[depth-1]
> IndexError: list index out of range

**Comment by Roromis** [comment]
Peux-tu m'envoyer l'adresse de ton forum par email à l'adresse `lalf arobase openmailbox dot org` pour que j'essaye de voir d'où vient le problème?

**Comment by Lemmy1916** [comment]
C'est fait, merci ;)

**Comment by Roromis** [comment]
Normalement ça devrait être corrigé dans la dernière version, tu peux l'installer en exécutant la commande suivante :

```
pip install -U https://github.com/Roromis/Lalf-Forumactif/archive/master.zip
```

Tu peux ensuite relancer le script directement sans toucher au fichier `save.pickle`. Si le problème n'est pas corrigé tu peux réouvrir le ticket.
