### ISSUE TITLE
KeyError: 'Nombre de sujets ouvert dans le forum'

### ISSUE THREAD

**Issue by jeffhpc** [Roromis/Lalf-Forumactif#77]
Bonjour à tous et merci pour le temps passé à la création et au debug du LALF !

Je crois avoir fait le tour des buggs déja signalés, du coup j'ouvre celui ci.

message d'erreur : 
                                                                                                    
Sauvegarde de l'état courant.                                                                                                       
ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (**KeyError('Nombre de sujets ouvert dans le forum**')), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
https://github.com/Roromis/Lalf-Forumactif/issues
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/lalf/__init__.py", line 58, in main
    bb.export()
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 112, in export
    self._export_()
  File "/root/.local/lib/python3.8/site-packages/lalf/bb.py", line 113, in _export_
    self.total_topics = int(stats["Nombre de sujets ouvert dans le forum"])
**KeyError: 'Nombre de sujets ouvert dans le forum'**

Je suis allé regardé dans les .py aux lignes indiquées pour essayer de comprendre ce qui peut coincer, mais sans résultat. 

Les stats du forum en question : 
Messages : 266635
**Nombre de sujets ouverts dans le forum : 13046**
Nombre d'utilisateurs : 996
Ouverture du forum : Jeu 7 Juin 2007 
Age du forum (jours) : 5399

**J'ai resynchronisé les statistiques de votre forum0**

Le nombre de sujets ne semble pas exceptionnel, du coup je ne comprends pas où celà coince.
Merci d'avance si quelqu'un à une piste de recherches... 

[debug.log](https://github.com/Roromis/Lalf-Forumactif/files/8309491/debug.log)

**Comment by kepon85** [comment]
Vieux motard que jamais : si tu veux palier à ce problème, regard la modification à apporter : https://github.com/Roromis/Lalf-Forumactif/pull/78/commits/39a962cb0d7a3401181c23841bf3e03930ef5c4e

David

**Comment by jeffhpc** [comment]
Bonjour David

Merci pour la réponse ;)

Effectivement, une fois corrigé, ça fonctionne beaucoup mieux. 

Problème résolu (je clos ce rapport), mais j'en ai maintenant un nouveau : https://github.com/Roromis/Lalf-Forumactif/issues/79

**Comment by jeffhpc** [comment]
Bonjour à tous 
J'ai relancé le script, qui cette fois commence son déroulé.
Sauvegarde ok des émoticones,
récupération des membre (2874)
INFO     : Récupération des groupes
INFO     : Récupération des forums
INFO     : Récupération du forum f46
DEBUG    : Récupération du forum f46 (page 0)
INFO     : Récupération du sujet 9073
INFO     : Récupération du message 103461 (sujet 7684)
INFO     : Récupération du message 103480 (sujet 7684)
INFO     : Récupération du sujet 1276
DEBUG    : Récupération des messages du sujet 1276 (page 0)
INFO     : Récupération du message 11322 (sujet 1276)
INFO     : Récupération du sujet 1109
DEBUG    : Récupération des messages du sujet 1109 (page 0)
DEBUG    : Connection au forum
DEBUG    : Récupération du sid
DEBUG    : Récupération du tid
INFO     : La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
DEBUG    : Connection au forum
DEBUG    : Récupération du sid
DEBUG    : Récupération du tid
INFO     : La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.

et le script rend la main... :/

pour info :
Messages	268209	Messages par jour	48.19
Nombre de sujets ouverts dans le forum	13107	Sujets par jour	2.35
Nombre d'utilisateurs	1015	Utilisateurs par jour	0.18
Ouverture du forum	Jeu 7 Juin 2007 - 18:45	Taille du répertoire des Avatars 4.33Mo

Une idée ? : /

**Comment by jeffhpc** [comment]
J'ai relancé le script, qui cette fois commence son déroulé.
Sauvegarde ok des émoticones,
récupération des membre (2874)
INFO     : Récupération des groupes
INFO     : Récupération des forums
INFO     : Récupération du forum f46
DEBUG    : Récupération du forum f46 (page 0)
INFO     : Récupération du sujet 9073
INFO     : Récupération du message 103461 (sujet 7684)
INFO     : Récupération du message 103480 (sujet 7684)
INFO     : Récupération du sujet 1276
DEBUG    : Récupération des messages du sujet 1276 (page 0)
INFO     : Récupération du message 11322 (sujet 1276)
INFO     : Récupération du sujet 1109
DEBUG    : Récupération des messages du sujet 1109 (page 0)
DEBUG    : Connection au forum
DEBUG    : Récupération du sid
DEBUG    : Récupération du tid
INFO     : La connexion a échoué au moins deux fois, attend 30 secondes
avant de réessayer.
DEBUG    : Connection au forum
DEBUG    : Récupération du sid
DEBUG    : Récupération du tid
INFO     : La connexion a échoué au moins deux fois, attend 30 secondes
avant de réessayer.

et le script rend la main... :/

pour info :
Messages *268209* Messages par jour *48.19*
Nombre de sujets ouverts dans le forum *13107* Sujets par jour *2.35*
Nombre d'utilisateurs *1015* Utilisateurs par jour *0.18*
Ouverture du forum *Jeu 7 Juin 2007 - 18:45* Taille du répertoire des
Avatars4,33Mo

merci d'avance pour votre aide.
